# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 441, 231))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.legs = QtWidgets.QWidget()
        self.legs.setObjectName("legs")
        self.checkB_zdc = QtWidgets.QCheckBox(self.legs)
        self.checkB_zdc.setGeometry(QtCore.QRect(100, 140, 101, 23))
        self.checkB_zdc.setObjectName("checkB_zdc")
        self.checkB_zbr = QtWidgets.QCheckBox(self.legs)
        self.checkB_zbr.setGeometry(QtCore.QRect(20, 110, 101, 23))
        self.checkB_zbr.setObjectName("checkB_zbr")
        self.checkB_zbc = QtWidgets.QCheckBox(self.legs)
        self.checkB_zbc.setGeometry(QtCore.QRect(100, 110, 101, 23))
        self.checkB_zbc.setObjectName("checkB_zbc")
        self.radioB_all_motors = QtWidgets.QRadioButton(self.legs)
        self.radioB_all_motors.setGeometry(QtCore.QRect(20, 50, 131, 23))
        self.radioB_all_motors.setChecked(True)
        self.radioB_all_motors.setObjectName("radioB_all_motors")
        self.radioB_single_motor = QtWidgets.QRadioButton(self.legs)
        self.radioB_single_motor.setGeometry(QtCore.QRect(20, 80, 151, 23))
        self.radioB_single_motor.setObjectName("radioB_single_motor")
        self.checkB_zdr = QtWidgets.QCheckBox(self.legs)
        self.checkB_zdr.setGeometry(QtCore.QRect(20, 140, 101, 23))
        self.checkB_zdr.setObjectName("checkB_zdr")
        self.label_12 = QtWidgets.QLabel(self.legs)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 131, 21))
        self.label_12.setObjectName("label_12")
        self.pushB_upwards = QtWidgets.QPushButton(self.legs)
        self.pushB_upwards.setGeometry(QtCore.QRect(200, 50, 81, 41))
        self.pushB_upwards.setObjectName("pushB_upwards")
        self.label_150 = QtWidgets.QLabel(self.legs)
        self.label_150.setGeometry(QtCore.QRect(200, 20, 68, 19))
        self.label_150.setObjectName("label_150")
        self.pushB_stop_legs = QtWidgets.QPushButton(self.legs)
        self.pushB_stop_legs.setGeometry(QtCore.QRect(200, 100, 181, 41))
        self.pushB_stop_legs.setObjectName("pushB_stop_legs")
        self.pushB_downwards = QtWidgets.QPushButton(self.legs)
        self.pushB_downwards.setGeometry(QtCore.QRect(290, 50, 91, 41))
        self.pushB_downwards.setObjectName("pushB_downwards")
        self.tabWidget.addTab(self.legs, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushB_start_x = QtWidgets.QPushButton(self.tab_2)
        self.pushB_start_x.setGeometry(QtCore.QRect(20, 100, 51, 41))
        self.pushB_start_x.setObjectName("pushB_start_x")
        self.dspinB_mm_axis_x = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.dspinB_mm_axis_x.setGeometry(QtCore.QRect(20, 60, 68, 25))
        self.dspinB_mm_axis_x.setProperty("value", 0.5)
        self.dspinB_mm_axis_x.setObjectName("dspinB_mm_axis_x")
        self.label_347 = QtWidgets.QLabel(self.tab_2)
        self.label_347.setGeometry(QtCore.QRect(20, 20, 141, 19))
        self.label_347.setObjectName("label_347")
        self.label_348 = QtWidgets.QLabel(self.tab_2)
        self.label_348.setGeometry(QtCore.QRect(100, 60, 91, 19))
        self.label_348.setObjectName("label_348")
        self.pushB_backwards = QtWidgets.QPushButton(self.tab_2)
        self.pushB_backwards.setGeometry(QtCore.QRect(290, 50, 81, 41))
        self.pushB_backwards.setObjectName("pushB_backwards")
        self.pushB_forwards = QtWidgets.QPushButton(self.tab_2)
        self.pushB_forwards.setGeometry(QtCore.QRect(200, 50, 81, 41))
        self.pushB_forwards.setObjectName("pushB_forwards")
        self.pushB_stop_x = QtWidgets.QPushButton(self.tab_2)
        self.pushB_stop_x.setGeometry(QtCore.QRect(200, 100, 171, 41))
        self.pushB_stop_x.setObjectName("pushB_stop_x")
        self.label_145 = QtWidgets.QLabel(self.tab_2)
        self.label_145.setGeometry(QtCore.QRect(200, 20, 68, 19))
        self.label_145.setObjectName("label_145")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 151, 19))
        self.label_5.setObjectName("label_5")
        self.pushB_stop_pr_cr = QtWidgets.QPushButton(self.tab_3)
        self.pushB_stop_pr_cr.setGeometry(QtCore.QRect(220, 160, 171, 41))
        self.pushB_stop_pr_cr.setObjectName("pushB_stop_pr_cr")
        self.pushB_start_pr_cr = QtWidgets.QPushButton(self.tab_3)
        self.pushB_start_pr_cr.setGeometry(QtCore.QRect(20, 100, 51, 41))
        self.pushB_start_pr_cr.setObjectName("pushB_start_pr_cr")
        self.label_151 = QtWidgets.QLabel(self.tab_3)
        self.label_151.setGeometry(QtCore.QRect(100, 60, 91, 19))
        self.label_151.setObjectName("label_151")
        self.dspinBox_deg_on_axis_pr_cr = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.dspinBox_deg_on_axis_pr_cr.setGeometry(QtCore.QRect(20, 60, 68, 25))
        self.dspinBox_deg_on_axis_pr_cr.setMaximum(180.0)
        self.dspinBox_deg_on_axis_pr_cr.setSingleStep(1.0)
        self.dspinBox_deg_on_axis_pr_cr.setProperty("value", 30.0)
        self.dspinBox_deg_on_axis_pr_cr.setObjectName("dspinBox_deg_on_axis_pr_cr")
        self.pushB_lefthand = QtWidgets.QPushButton(self.tab_3)
        self.pushB_lefthand.setGeometry(QtCore.QRect(220, 110, 81, 41))
        self.pushB_lefthand.setObjectName("pushB_lefthand")
        self.pushB_righthand = QtWidgets.QPushButton(self.tab_3)
        self.pushB_righthand.setGeometry(QtCore.QRect(310, 110, 121, 41))
        self.pushB_righthand.setObjectName("pushB_righthand")
        self.checkB_pr = QtWidgets.QCheckBox(self.tab_3)
        self.checkB_pr.setGeometry(QtCore.QRect(220, 50, 119, 23))
        self.checkB_pr.setObjectName("checkB_pr")
        self.checkB_cr = QtWidgets.QCheckBox(self.tab_3)
        self.checkB_cr.setGeometry(QtCore.QRect(220, 80, 119, 23))
        self.checkB_cr.setObjectName("checkB_cr")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(220, 20, 68, 19))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_162 = QtWidgets.QLabel(self.tab)
        self.label_162.setGeometry(QtCore.QRect(10, 80, 68, 19))
        self.label_162.setText("")
        self.label_162.setObjectName("label_162")
        self.label_177 = QtWidgets.QLabel(self.tab)
        self.label_177.setGeometry(QtCore.QRect(20, 20, 68, 19))
        self.label_177.setObjectName("label_177")
        self.pushB_switch = QtWidgets.QPushButton(self.tab)
        self.pushB_switch.setGeometry(QtCore.QRect(20, 50, 121, 34))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_switch.setFont(font)
        self.pushB_switch.setObjectName("pushB_switch")
        self.tabWidget.addTab(self.tab, "")
        self.stackedW_settings_leg = QtWidgets.QFrame(self.centralwidget)
        self.stackedW_settings_leg.setGeometry(QtCore.QRect(440, 390, 341, 251))
        self.stackedW_settings_leg.setObjectName("stackedW_settings_leg")
        self.spinB_max_RPM = QtWidgets.QSpinBox(self.stackedW_settings_leg)
        self.spinB_max_RPM.setGeometry(QtCore.QRect(20, 220, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.spinB_max_RPM.setFont(font)
        self.spinB_max_RPM.setMinimum(1)
        self.spinB_max_RPM.setMaximum(1000)
        self.spinB_max_RPM.setProperty("value", 120)
        self.spinB_max_RPM.setObjectName("spinB_max_RPM")
        self.label_41 = QtWidgets.QLabel(self.stackedW_settings_leg)
        self.label_41.setGeometry(QtCore.QRect(80, 100, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_10 = QtWidgets.QLabel(self.stackedW_settings_leg)
        self.label_10.setGeometry(QtCore.QRect(250, 120, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.spinB_fine = QtWidgets.QSpinBox(self.stackedW_settings_leg)
        self.spinB_fine.setGeometry(QtCore.QRect(20, 100, 41, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.spinB_fine.setFont(font)
        self.spinB_fine.setMinimum(1)
        self.spinB_fine.setMaximum(32)
        self.spinB_fine.setProperty("value", 1)
        self.spinB_fine.setObjectName("spinB_fine")
        self.label_16 = QtWidgets.QLabel(self.stackedW_settings_leg)
        self.label_16.setGeometry(QtCore.QRect(20, 0, 68, 21))
        self.label_16.setObjectName("label_16")
        self.label_42 = QtWidgets.QLabel(self.stackedW_settings_leg)
        self.label_42.setGeometry(QtCore.QRect(80, 130, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_45 = QtWidgets.QLabel(self.stackedW_settings_leg)
        self.label_45.setGeometry(QtCore.QRect(110, 220, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_40 = QtWidgets.QLabel(self.stackedW_settings_leg)
        self.label_40.setGeometry(QtCore.QRect(20, 20, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.spinB_mm_per_rev = QtWidgets.QDoubleSpinBox(self.stackedW_settings_leg)
        self.spinB_mm_per_rev.setGeometry(QtCore.QRect(180, 100, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.spinB_mm_per_rev.setFont(font)
        self.spinB_mm_per_rev.setSingleStep(0.0)
        self.spinB_mm_per_rev.setProperty("value", 0.5)
        self.spinB_mm_per_rev.setObjectName("spinB_mm_per_rev")
        self.spinB_coarse = QtWidgets.QSpinBox(self.stackedW_settings_leg)
        self.spinB_coarse.setGeometry(QtCore.QRect(20, 130, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.spinB_coarse.setFont(font)
        self.spinB_coarse.setMinimum(1)
        self.spinB_coarse.setMaximum(124)
        self.spinB_coarse.setProperty("value", 10)
        self.spinB_coarse.setObjectName("spinB_coarse")
        self.label_44 = QtWidgets.QLabel(self.stackedW_settings_leg)
        self.label_44.setGeometry(QtCore.QRect(250, 100, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.spinB_mstep_res = QtWidgets.QSpinBox(self.stackedW_settings_leg)
        self.spinB_mstep_res.setGeometry(QtCore.QRect(20, 160, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.spinB_mstep_res.setFont(font)
        self.spinB_mstep_res.setMinimum(0)
        self.spinB_mstep_res.setMaximum(8)
        self.spinB_mstep_res.setSingleStep(1)
        self.spinB_mstep_res.setProperty("value", 4)
        self.spinB_mstep_res.setObjectName("spinB_mstep_res")
        self.pushB_invert = QtWidgets.QPushButton(self.stackedW_settings_leg)
        self.pushB_invert.setGeometry(QtCore.QRect(20, 190, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_invert.setFont(font)
        self.pushB_invert.setObjectName("pushB_invert")
        self.label_43 = QtWidgets.QLabel(self.stackedW_settings_leg)
        self.label_43.setGeometry(QtCore.QRect(60, 160, 171, 19))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.spinBox_RPM = QtWidgets.QSpinBox(self.stackedW_settings_leg)
        self.spinBox_RPM.setGeometry(QtCore.QRect(180, 130, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.spinBox_RPM.setFont(font)
        self.spinBox_RPM.setProperty("value", 30)
        self.spinBox_RPM.setObjectName("spinBox_RPM")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 10, 171, 19))
        self.label.setObjectName("label")
        self.pushB_overwrite_u = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_overwrite_u.setGeometry(QtCore.QRect(460, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_overwrite_u.setFont(font)
        self.pushB_overwrite_u.setObjectName("pushB_overwrite_u")
        self.pushB_overwrite_d = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_overwrite_d.setGeometry(QtCore.QRect(460, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_overwrite_d.setFont(font)
        self.pushB_overwrite_d.setObjectName("pushB_overwrite_d")
        self.lcd_pos_u = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pos_u.setGeometry(QtCore.QRect(560, 90, 64, 21))
        self.lcd_pos_u.setObjectName("lcd_pos_u")
        self.lcd_pos_d = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pos_d.setGeometry(QtCore.QRect(560, 120, 64, 21))
        self.lcd_pos_d.setObjectName("lcd_pos_d")
        self.label_overwrite_u = QtWidgets.QLabel(self.centralwidget)
        self.label_overwrite_u.setGeometry(QtCore.QRect(670, 90, 68, 19))
        self.label_overwrite_u.setObjectName("label_overwrite_u")
        self.label_overwrite_d = QtWidgets.QLabel(self.centralwidget)
        self.label_overwrite_d.setGeometry(QtCore.QRect(670, 120, 68, 19))
        self.label_overwrite_d.setObjectName("label_overwrite_d")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(460, 70, 101, 19))
        self.label_15.setObjectName("label_15")
        self.label_141 = QtWidgets.QLabel(self.centralwidget)
        self.label_141.setGeometry(QtCore.QRect(470, 40, 68, 19))
        self.label_141.setObjectName("label_141")
        self.label_142 = QtWidgets.QLabel(self.centralwidget)
        self.label_142.setGeometry(QtCore.QRect(540, 40, 111, 19))
        self.label_142.setObjectName("label_142")
        self.label_143 = QtWidgets.QLabel(self.centralwidget)
        self.label_143.setGeometry(QtCore.QRect(660, 40, 101, 19))
        self.label_143.setObjectName("label_143")
        self.label_overwrite_a = QtWidgets.QLabel(self.centralwidget)
        self.label_overwrite_a.setGeometry(QtCore.QRect(670, 170, 68, 19))
        self.label_overwrite_a.setObjectName("label_overwrite_a")
        self.label_overwrite_b = QtWidgets.QLabel(self.centralwidget)
        self.label_overwrite_b.setGeometry(QtCore.QRect(670, 200, 68, 19))
        self.label_overwrite_b.setObjectName("label_overwrite_b")
        self.lcd_pos_a = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pos_a.setGeometry(QtCore.QRect(560, 170, 64, 21))
        self.lcd_pos_a.setObjectName("lcd_pos_a")
        self.lcd_pos_b = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pos_b.setGeometry(QtCore.QRect(560, 200, 64, 21))
        self.lcd_pos_b.setObjectName("lcd_pos_b")
        self.pushB_overwrite_b = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_overwrite_b.setGeometry(QtCore.QRect(460, 200, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_overwrite_b.setFont(font)
        self.pushB_overwrite_b.setObjectName("pushB_overwrite_b")
        self.pushB_overwrite_a = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_overwrite_a.setGeometry(QtCore.QRect(460, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_overwrite_a.setFont(font)
        self.pushB_overwrite_a.setObjectName("pushB_overwrite_a")
        self.label_overwrite_x = QtWidgets.QLabel(self.centralwidget)
        self.label_overwrite_x.setGeometry(QtCore.QRect(670, 250, 68, 19))
        self.label_overwrite_x.setObjectName("label_overwrite_x")
        self.label_overwrite_y = QtWidgets.QLabel(self.centralwidget)
        self.label_overwrite_y.setGeometry(QtCore.QRect(670, 280, 68, 19))
        self.label_overwrite_y.setObjectName("label_overwrite_y")
        self.lcd_pos_x = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pos_x.setGeometry(QtCore.QRect(560, 250, 64, 21))
        self.lcd_pos_x.setObjectName("lcd_pos_x")
        self.lcd_pos_y = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pos_y.setGeometry(QtCore.QRect(560, 280, 64, 21))
        self.lcd_pos_y.setObjectName("lcd_pos_y")
        self.pushB_overwrite_y = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_overwrite_y.setGeometry(QtCore.QRect(460, 280, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_overwrite_y.setFont(font)
        self.pushB_overwrite_y.setObjectName("pushB_overwrite_y")
        self.pushB_overwrite_x = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_overwrite_x.setGeometry(QtCore.QRect(460, 250, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_overwrite_x.setFont(font)
        self.pushB_overwrite_x.setObjectName("pushB_overwrite_x")
        self.label_overwrite_r = QtWidgets.QLabel(self.centralwidget)
        self.label_overwrite_r.setGeometry(QtCore.QRect(670, 330, 68, 19))
        self.label_overwrite_r.setObjectName("label_overwrite_r")
        self.label_overwrite_i = QtWidgets.QLabel(self.centralwidget)
        self.label_overwrite_i.setGeometry(QtCore.QRect(670, 360, 68, 19))
        self.label_overwrite_i.setObjectName("label_overwrite_i")
        self.lcd_pos_r = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pos_r.setGeometry(QtCore.QRect(560, 330, 64, 21))
        self.lcd_pos_r.setObjectName("lcd_pos_r")
        self.lcd_pos_i = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pos_i.setGeometry(QtCore.QRect(560, 360, 64, 21))
        self.lcd_pos_i.setObjectName("lcd_pos_i")
        self.pushB_overwrite_i = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_overwrite_i.setGeometry(QtCore.QRect(460, 360, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_overwrite_i.setFont(font)
        self.pushB_overwrite_i.setObjectName("pushB_overwrite_i")
        self.pushB_overwrite_r = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_overwrite_r.setGeometry(QtCore.QRect(460, 330, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushB_overwrite_r.setFont(font)
        self.pushB_overwrite_r.setObjectName("pushB_overwrite_r")
        self.label_163 = QtWidgets.QLabel(self.centralwidget)
        self.label_163.setGeometry(QtCore.QRect(460, 150, 81, 19))
        self.label_163.setObjectName("label_163")
        self.label_170 = QtWidgets.QLabel(self.centralwidget)
        self.label_170.setGeometry(QtCore.QRect(460, 230, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_170.setFont(font)
        self.label_170.setObjectName("label_170")
        self.label_171 = QtWidgets.QLabel(self.centralwidget)
        self.label_171.setGeometry(QtCore.QRect(460, 310, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_171.setFont(font)
        self.label_171.setObjectName("label_171")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 230, 421, 401))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_494 = QtWidgets.QLabel(self.frame)
        self.label_494.setGeometry(QtCore.QRect(10, 80, 361, 331))
        self.label_494.setObjectName("label_494")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 68, 19))
        self.label_11.setObjectName("label_11")
        self.radioB_permanent = QtWidgets.QRadioButton(self.frame)
        self.radioB_permanent.setGeometry(QtCore.QRect(10, 60, 119, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioB_permanent.setFont(font)
        self.radioB_permanent.setObjectName("radioB_permanent")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioB_permanent)
        self.radioB_when_pushed = QtWidgets.QRadioButton(self.frame)
        self.radioB_when_pushed.setGeometry(QtCore.QRect(120, 60, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioB_when_pushed.setFont(font)
        self.radioB_when_pushed.setObjectName("radioB_when_pushed")
        self.buttonGroup.addButton(self.radioB_when_pushed)
        self.radioB_key_control = QtWidgets.QRadioButton(self.frame)
        self.radioB_key_control.setGeometry(QtCore.QRect(240, 60, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioB_key_control.setFont(font)
        self.radioB_key_control.setObjectName("radioB_key_control")
        self.buttonGroup.addButton(self.radioB_key_control)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkB_zdc.setText(_translate("MainWindow", "ZDC"))
        self.checkB_zbr.setText(_translate("MainWindow", "ZBR"))
        self.checkB_zbc.setText(_translate("MainWindow", "ZBC"))
        self.radioB_all_motors.setText(_translate("MainWindow", "all leg motors "))
        self.radioB_single_motor.setText(_translate("MainWindow", "select leg motor"))
        self.checkB_zdr.setText(_translate("MainWindow", "ZDR"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600;\">Motor selection</span></p></body></html>"))
        self.pushB_upwards.setText(_translate("MainWindow", "upwards"))
        self.label_150.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600;\">Rotate</span></p></body></html>"))
        self.pushB_stop_legs.setText(_translate("MainWindow", "Stop"))
        self.pushB_downwards.setText(_translate("MainWindow", "downwards"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.legs), _translate("MainWindow", "Leg control"))
        self.pushB_start_x.setText(_translate("MainWindow", "Start"))
        self.label_347.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600;\">Absolute position </span></p></body></html>"))
        self.label_348.setText(_translate("MainWindow", "mm on axis"))
        self.pushB_backwards.setText(_translate("MainWindow", "backwards"))
        self.pushB_forwards.setText(_translate("MainWindow", "forwards"))
        self.pushB_stop_x.setText(_translate("MainWindow", "Stop"))
        self.label_145.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600;\">Rotate</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "X direction"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600;\">Absolute position</span></p></body></html>"))
        self.pushB_stop_pr_cr.setText(_translate("MainWindow", "Stop"))
        self.pushB_start_pr_cr.setText(_translate("MainWindow", "Start"))
        self.label_151.setText(_translate("MainWindow", "deg on axis"))
        self.pushB_lefthand.setText(_translate("MainWindow", "clockwise"))
        self.pushB_righthand.setText(_translate("MainWindow", "counterclockwise"))
        self.checkB_pr.setText(_translate("MainWindow", "PR"))
        self.checkB_cr.setText(_translate("MainWindow", "CR"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600;\">Rotate</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "PR / CR"))
        self.label_177.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600;\">S motor</span></p></body></html>"))
        self.pushB_switch.setText(_translate("MainWindow", "next specimen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Switch"))
        self.label_41.setText(_translate("MainWindow", "fine"))
        self.label_10.setText(_translate("MainWindow", "RPM"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Settings</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "coarse"))
        self.label_45.setText(_translate("MainWindow", "max RPM"))
        self.label_40.setText(_translate("MainWindow", "keyboard control: \n"
"press up and down for fine steps \n"
"press left and right for coarse steps "))
        self.label_44.setText(_translate("MainWindow", "mm per rev"))
        self.pushB_invert.setText(_translate("MainWindow", "invert direction"))
        self.label_43.setText(_translate("MainWindow", "microstep multiplicator"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Go to saved position</span></p></body></html>"))
        self.pushB_overwrite_u.setText(_translate("MainWindow", "Pos Up"))
        self.pushB_overwrite_d.setText(_translate("MainWindow", "Pos Down"))
        self.label_overwrite_u.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Ctrl + U</span></p></body></html>"))
        self.label_overwrite_d.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Ctrl + D</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Leg positions</span></p></body></html>"))
        self.label_141.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">position</span></p></body></html>"))
        self.label_142.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">mm / deg on axis</span></p></body></html>"))
        self.label_143.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">overwrite pos</span></p></body></html>"))
        self.label_overwrite_a.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Ctrl + A</span></p></body></html>"))
        self.label_overwrite_b.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Ctrl + B</span></p></body></html>"))
        self.pushB_overwrite_b.setText(_translate("MainWindow", "Pos B"))
        self.pushB_overwrite_a.setText(_translate("MainWindow", "Pos A"))
        self.label_overwrite_x.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Ctrl + X</span></p></body></html>"))
        self.label_overwrite_y.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Ctrl + Y</span></p></body></html>"))
        self.pushB_overwrite_y.setText(_translate("MainWindow", "Pos Y"))
        self.pushB_overwrite_x.setText(_translate("MainWindow", "Pos X"))
        self.label_overwrite_r.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Ctrl + R</span></p></body></html>"))
        self.label_overwrite_i.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Ctrl + I</span></p></body></html>"))
        self.pushB_overwrite_i.setText(_translate("MainWindow", "Pos ion beam"))
        self.pushB_overwrite_r.setText(_translate("MainWindow", "Pos raman"))
        self.label_163.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">X positions</span></p></body></html>"))
        self.label_170.setText(_translate("MainWindow", "PR"))
        self.label_171.setText(_translate("MainWindow", "CR"))
        self.label_494.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Info</span></p><p><span style=\" font-size:7pt;\">- mode when pushed sends signals to motor continously,</span></p><p><span style=\" font-size:7pt;\">as long as button is pressed down </span></p><p><span style=\" font-size:7pt;\">- mode keyboard control is for small adjustments </span></p><p><span style=\" font-size:7pt;\">(-&gt; settings)</span></p><p><span style=\" font-size:7pt;\">- for PR / CR deg on axis are used for LCD values,</span></p><p><span style=\" font-size:7pt;\">for the rest mm on axis </span></p><p><span style=\" font-size:7pt;\">- the value in microstep resolution spinbox is the exponent</span></p><p><span style=\" font-size:7pt;\">for the base 2 (-&gt; so by default microstep res. is 16)</span></p><p><span style=\" font-size:7pt;\">- usually 30 - 120 RPM is a good choice. </span></p><p><span style=\" font-size:7pt;\">At higher RPM, torque decreases.</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Modes </span></p></body></html>"))
        self.radioB_permanent.setText(_translate("MainWindow", "permanent"))
        self.radioB_when_pushed.setText(_translate("MainWindow", "when pushed"))
        self.radioB_key_control.setText(_translate("MainWindow", "keyboard control"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

