# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.legs = QtWidgets.QWidget()
        self.legs.setObjectName("legs")
        self.groupB_mselection_leg = QtWidgets.QGroupBox(self.legs)
        self.groupB_mselection_leg.setGeometry(QtCore.QRect(10, 10, 761, 171))
        self.groupB_mselection_leg.setFlat(True)
        self.groupB_mselection_leg.setCheckable(True)
        self.groupB_mselection_leg.setObjectName("groupB_mselection_leg")
        self.radioB_all_motors = QtWidgets.QRadioButton(self.groupB_mselection_leg)
        self.radioB_all_motors.setGeometry(QtCore.QRect(10, 30, 131, 23))
        self.radioB_all_motors.setChecked(True)
        self.radioB_all_motors.setObjectName("radioB_all_motors")
        self.radioB_single_motor = QtWidgets.QRadioButton(self.groupB_mselection_leg)
        self.radioB_single_motor.setGeometry(QtCore.QRect(10, 70, 151, 23))
        self.radioB_single_motor.setObjectName("radioB_single_motor")
        self.checkB_zbr = QtWidgets.QCheckBox(self.groupB_mselection_leg)
        self.checkB_zbr.setGeometry(QtCore.QRect(10, 100, 101, 23))
        self.checkB_zbr.setObjectName("checkB_zbr")
        self.checkB_zbc = QtWidgets.QCheckBox(self.groupB_mselection_leg)
        self.checkB_zbc.setGeometry(QtCore.QRect(110, 100, 101, 23))
        self.checkB_zbc.setObjectName("checkB_zbc")
        self.checkB_zdr = QtWidgets.QCheckBox(self.groupB_mselection_leg)
        self.checkB_zdr.setGeometry(QtCore.QRect(10, 130, 101, 23))
        self.checkB_zdr.setObjectName("checkB_zdr")
        self.checkB_zdc = QtWidgets.QCheckBox(self.groupB_mselection_leg)
        self.checkB_zdc.setGeometry(QtCore.QRect(110, 130, 101, 23))
        self.checkB_zdc.setObjectName("checkB_zdc")
        self.pushB_pos_up = QtWidgets.QPushButton(self.groupB_mselection_leg)
        self.pushB_pos_up.setGeometry(QtCore.QRect(300, 50, 131, 34))
        self.pushB_pos_up.setObjectName("pushB_pos_up")
        self.pushB_pos_down = QtWidgets.QPushButton(self.groupB_mselection_leg)
        self.pushB_pos_down.setGeometry(QtCore.QRect(300, 90, 131, 34))
        self.pushB_pos_down.setObjectName("pushB_pos_down")
        self.lcd_pos_up = QtWidgets.QLCDNumber(self.groupB_mselection_leg)
        self.lcd_pos_up.setGeometry(QtCore.QRect(450, 50, 81, 31))
        self.lcd_pos_up.setObjectName("lcd_pos_up")
        self.lcd_pos_down = QtWidgets.QLCDNumber(self.groupB_mselection_leg)
        self.lcd_pos_down.setGeometry(QtCore.QRect(450, 90, 81, 31))
        self.lcd_pos_down.setProperty("value", 250.0)
        self.lcd_pos_down.setObjectName("lcd_pos_down")
        self.label_7 = QtWidgets.QLabel(self.groupB_mselection_leg)
        self.label_7.setGeometry(QtCore.QRect(310, 20, 111, 19))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupB_mselection_leg)
        self.label_8.setGeometry(QtCore.QRect(450, 20, 91, 19))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupB_mselection_leg)
        self.label_9.setGeometry(QtCore.QRect(560, 20, 131, 19))
        self.label_9.setObjectName("label_9")
        self.label_overwrite_up = QtWidgets.QLabel(self.groupB_mselection_leg)
        self.label_overwrite_up.setGeometry(QtCore.QRect(580, 50, 68, 31))
        self.label_overwrite_up.setObjectName("label_overwrite_up")
        self.label_overwrite_down = QtWidgets.QLabel(self.groupB_mselection_leg)
        self.label_overwrite_down.setGeometry(QtCore.QRect(580, 90, 68, 31))
        self.label_overwrite_down.setObjectName("label_overwrite_down")
        self.groupB_when_pushed_leg = QtWidgets.QGroupBox(self.legs)
        self.groupB_when_pushed_leg.setGeometry(QtCore.QRect(10, 350, 411, 171))
        self.groupB_when_pushed_leg.setFlat(True)
        self.groupB_when_pushed_leg.setCheckable(True)
        self.groupB_when_pushed_leg.setChecked(False)
        self.groupB_when_pushed_leg.setObjectName("groupB_when_pushed_leg")
        self.pushB_forwards_leg = QtWidgets.QPushButton(self.groupB_when_pushed_leg)
        self.pushB_forwards_leg.setGeometry(QtCore.QRect(20, 50, 101, 31))
        self.pushB_forwards_leg.setAutoRepeat(True)
        self.pushB_forwards_leg.setObjectName("pushB_forwards_leg")
        self.pushB_backwards_leg = QtWidgets.QPushButton(self.groupB_when_pushed_leg)
        self.pushB_backwards_leg.setGeometry(QtCore.QRect(20, 90, 101, 31))
        self.pushB_backwards_leg.setAutoRepeat(True)
        self.pushB_backwards_leg.setObjectName("pushB_backwards_leg")
        self.label_10 = QtWidgets.QLabel(self.groupB_when_pushed_leg)
        self.label_10.setGeometry(QtCore.QRect(140, 50, 68, 19))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.spinB_RPM_when_pushed_leg = QtWidgets.QSpinBox(self.groupB_when_pushed_leg)
        self.spinB_RPM_when_pushed_leg.setGeometry(QtCore.QRect(150, 130, 81, 25))
        self.spinB_RPM_when_pushed_leg.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinB_RPM_when_pushed_leg.setProperty("value", 30)
        self.spinB_RPM_when_pushed_leg.setObjectName("spinB_RPM_when_pushed_leg")
        self.label_11 = QtWidgets.QLabel(self.groupB_when_pushed_leg)
        self.label_11.setGeometry(QtCore.QRect(20, 130, 68, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupB_when_pushed_leg)
        self.label_12.setGeometry(QtCore.QRect(150, 50, 161, 71))
        self.label_12.setObjectName("label_12")
        self.groupB_permanent_leg = QtWidgets.QGroupBox(self.legs)
        self.groupB_permanent_leg.setGeometry(QtCore.QRect(10, 180, 411, 161))
        self.groupB_permanent_leg.setFlat(True)
        self.groupB_permanent_leg.setCheckable(True)
        self.groupB_permanent_leg.setChecked(False)
        self.groupB_permanent_leg.setObjectName("groupB_permanent_leg")
        self.radioB_forwards_leg = QtWidgets.QRadioButton(self.groupB_permanent_leg)
        self.radioB_forwards_leg.setGeometry(QtCore.QRect(10, 60, 119, 23))
        self.radioB_forwards_leg.setChecked(True)
        self.radioB_forwards_leg.setObjectName("radioB_forwards_leg")
        self.radioB_backwards_leg = QtWidgets.QRadioButton(self.groupB_permanent_leg)
        self.radioB_backwards_leg.setGeometry(QtCore.QRect(10, 90, 119, 23))
        self.radioB_backwards_leg.setObjectName("radioB_backwards_leg")
        self.pushB_stop_leg = QtWidgets.QPushButton(self.groupB_permanent_leg)
        self.pushB_stop_leg.setGeometry(QtCore.QRect(250, 60, 61, 51))
        self.pushB_stop_leg.setObjectName("pushB_stop_leg")
        self.spinB_RPM_permanent_leg = QtWidgets.QSpinBox(self.groupB_permanent_leg)
        self.spinB_RPM_permanent_leg.setGeometry(QtCore.QRect(140, 130, 81, 25))
        self.spinB_RPM_permanent_leg.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinB_RPM_permanent_leg.setKeyboardTracking(False)
        self.spinB_RPM_permanent_leg.setProperty("value", 30)
        self.spinB_RPM_permanent_leg.setObjectName("spinB_RPM_permanent_leg")
        self.label_13 = QtWidgets.QLabel(self.groupB_permanent_leg)
        self.label_13.setGeometry(QtCore.QRect(10, 130, 68, 19))
        self.label_13.setObjectName("label_13")
        self.pushB_start_leg = QtWidgets.QPushButton(self.groupB_permanent_leg)
        self.pushB_start_leg.setGeometry(QtCore.QRect(160, 60, 61, 51))
        self.pushB_start_leg.setObjectName("pushB_start_leg")
        self.groupB_key_control_leg = QtWidgets.QGroupBox(self.legs)
        self.groupB_key_control_leg.setGeometry(QtCore.QRect(10, 520, 751, 91))
        self.groupB_key_control_leg.setFlat(True)
        self.groupB_key_control_leg.setCheckable(True)
        self.groupB_key_control_leg.setChecked(False)
        self.groupB_key_control_leg.setObjectName("groupB_key_control_leg")
        self.label_21 = QtWidgets.QLabel(self.groupB_key_control_leg)
        self.label_21.setGeometry(QtCore.QRect(20, 30, 651, 61))
        self.label_21.setObjectName("label_21")
        self.label_14 = QtWidgets.QLabel(self.legs)
        self.label_14.setGeometry(QtCore.QRect(20, 610, 681, 61))
        self.label_14.setObjectName("label_14")
        self.stackedW_settings_leg = QtWidgets.QStackedWidget(self.legs)
        self.stackedW_settings_leg.setGeometry(QtCore.QRect(440, 200, 331, 301))
        self.stackedW_settings_leg.setObjectName("stackedW_settings_leg")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.spinB_zbc_mm_per_rev = QtWidgets.QDoubleSpinBox(self.page)
        self.spinB_zbc_mm_per_rev.setGeometry(QtCore.QRect(120, 100, 61, 25))
        self.spinB_zbc_mm_per_rev.setMinimum(0.0)
        self.spinB_zbc_mm_per_rev.setProperty("value", 0.5)
        self.spinB_zbc_mm_per_rev.setObjectName("spinB_zbc_mm_per_rev")
        self.label_46 = QtWidgets.QLabel(self.page)
        self.label_46.setGeometry(QtCore.QRect(80, 100, 68, 19))
        self.label_46.setObjectName("label_46")
        self.spinB_zbc_fine = QtWidgets.QSpinBox(self.page)
        self.spinB_zbc_fine.setGeometry(QtCore.QRect(10, 100, 41, 25))
        self.spinB_zbc_fine.setMinimum(1)
        self.spinB_zbc_fine.setMaximum(32)
        self.spinB_zbc_fine.setProperty("value", 1)
        self.spinB_zbc_fine.setObjectName("spinB_zbc_fine")
        self.label_47 = QtWidgets.QLabel(self.page)
        self.label_47.setGeometry(QtCore.QRect(100, 190, 151, 19))
        self.label_47.setObjectName("label_47")
        self.pushB_zbc_invert = QtWidgets.QPushButton(self.page)
        self.pushB_zbc_invert.setGeometry(QtCore.QRect(10, 220, 131, 34))
        self.pushB_zbc_invert.setObjectName("pushB_zbc_invert")
        self.label_48 = QtWidgets.QLabel(self.page)
        self.label_48.setGeometry(QtCore.QRect(80, 140, 68, 19))
        self.label_48.setObjectName("label_48")
        self.spinB_zbc_coarse = QtWidgets.QSpinBox(self.page)
        self.spinB_zbc_coarse.setGeometry(QtCore.QRect(10, 140, 51, 25))
        self.spinB_zbc_coarse.setMinimum(1)
        self.spinB_zbc_coarse.setMaximum(124)
        self.spinB_zbc_coarse.setProperty("value", 10)
        self.spinB_zbc_coarse.setObjectName("spinB_zbc_coarse")
        self.label_49 = QtWidgets.QLabel(self.page)
        self.label_49.setGeometry(QtCore.QRect(10, 0, 68, 19))
        self.label_49.setObjectName("label_49")
        self.spinB_zbc_max_RPM = QtWidgets.QSpinBox(self.page)
        self.spinB_zbc_max_RPM.setGeometry(QtCore.QRect(10, 260, 81, 25))
        self.spinB_zbc_max_RPM.setMinimum(1)
        self.spinB_zbc_max_RPM.setMaximum(1000)
        self.spinB_zbc_max_RPM.setProperty("value", 120)
        self.spinB_zbc_max_RPM.setObjectName("spinB_zbc_max_RPM")
        self.label_50 = QtWidgets.QLabel(self.page)
        self.label_50.setGeometry(QtCore.QRect(10, 30, 261, 51))
        self.label_50.setObjectName("label_50")
        self.spinB_zbc_steps_per_rev = QtWidgets.QSpinBox(self.page)
        self.spinB_zbc_steps_per_rev.setGeometry(QtCore.QRect(10, 190, 81, 25))
        self.spinB_zbc_steps_per_rev.setMinimum(1)
        self.spinB_zbc_steps_per_rev.setMaximum(51200)
        self.spinB_zbc_steps_per_rev.setProperty("value", 400)
        self.spinB_zbc_steps_per_rev.setObjectName("spinB_zbc_steps_per_rev")
        self.label_51 = QtWidgets.QLabel(self.page)
        self.label_51.setGeometry(QtCore.QRect(100, 260, 68, 19))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.page)
        self.label_52.setGeometry(QtCore.QRect(180, 100, 151, 19))
        self.label_52.setObjectName("label_52")
        self.stackedW_settings_leg.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_53 = QtWidgets.QLabel(self.page_3)
        self.label_53.setGeometry(QtCore.QRect(190, 100, 151, 19))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.page_3)
        self.label_54.setGeometry(QtCore.QRect(10, 10, 68, 19))
        self.label_54.setObjectName("label_54")
        self.spinB_zdr_fine = QtWidgets.QSpinBox(self.page_3)
        self.spinB_zdr_fine.setGeometry(QtCore.QRect(10, 100, 41, 25))
        self.spinB_zdr_fine.setMinimum(1)
        self.spinB_zdr_fine.setMaximum(32)
        self.spinB_zdr_fine.setObjectName("spinB_zdr_fine")
        self.label_55 = QtWidgets.QLabel(self.page_3)
        self.label_55.setGeometry(QtCore.QRect(70, 140, 68, 19))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_3)
        self.label_56.setGeometry(QtCore.QRect(70, 100, 68, 19))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.page_3)
        self.label_57.setGeometry(QtCore.QRect(100, 260, 68, 19))
        self.label_57.setObjectName("label_57")
        self.spinB_zdr_steps_per_rev = QtWidgets.QSpinBox(self.page_3)
        self.spinB_zdr_steps_per_rev.setGeometry(QtCore.QRect(10, 190, 81, 25))
        self.spinB_zdr_steps_per_rev.setMinimum(1)
        self.spinB_zdr_steps_per_rev.setMaximum(51200)
        self.spinB_zdr_steps_per_rev.setProperty("value", 400)
        self.spinB_zdr_steps_per_rev.setObjectName("spinB_zdr_steps_per_rev")
        self.label_58 = QtWidgets.QLabel(self.page_3)
        self.label_58.setGeometry(QtCore.QRect(100, 190, 151, 19))
        self.label_58.setObjectName("label_58")
        self.spinB_zdr_max_RPM = QtWidgets.QSpinBox(self.page_3)
        self.spinB_zdr_max_RPM.setGeometry(QtCore.QRect(10, 260, 81, 25))
        self.spinB_zdr_max_RPM.setMinimum(1)
        self.spinB_zdr_max_RPM.setMaximum(1000)
        self.spinB_zdr_max_RPM.setProperty("value", 120)
        self.spinB_zdr_max_RPM.setObjectName("spinB_zdr_max_RPM")
        self.pushB_zdr_invert = QtWidgets.QPushButton(self.page_3)
        self.pushB_zdr_invert.setGeometry(QtCore.QRect(10, 220, 131, 34))
        self.pushB_zdr_invert.setObjectName("pushB_zdr_invert")
        self.spinB_zdr_coarse = QtWidgets.QSpinBox(self.page_3)
        self.spinB_zdr_coarse.setGeometry(QtCore.QRect(10, 140, 51, 25))
        self.spinB_zdr_coarse.setMinimum(1)
        self.spinB_zdr_coarse.setMaximum(124)
        self.spinB_zdr_coarse.setProperty("value", 10)
        self.spinB_zdr_coarse.setObjectName("spinB_zdr_coarse")
        self.spinB_zdr_mm_per_rev = QtWidgets.QDoubleSpinBox(self.page_3)
        self.spinB_zdr_mm_per_rev.setGeometry(QtCore.QRect(120, 100, 61, 25))
        self.spinB_zdr_mm_per_rev.setProperty("value", 0.5)
        self.spinB_zdr_mm_per_rev.setObjectName("spinB_zdr_mm_per_rev")
        self.label_59 = QtWidgets.QLabel(self.page_3)
        self.label_59.setGeometry(QtCore.QRect(10, 30, 261, 61))
        self.label_59.setObjectName("label_59")
        self.stackedW_settings_leg.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_60 = QtWidgets.QLabel(self.page_4)
        self.label_60.setGeometry(QtCore.QRect(190, 100, 151, 19))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.page_4)
        self.label_61.setGeometry(QtCore.QRect(10, 0, 68, 19))
        self.label_61.setObjectName("label_61")
        self.spinB_zdc_fine = QtWidgets.QSpinBox(self.page_4)
        self.spinB_zdc_fine.setGeometry(QtCore.QRect(10, 100, 41, 25))
        self.spinB_zdc_fine.setMinimum(1)
        self.spinB_zdc_fine.setMaximum(32)
        self.spinB_zdc_fine.setProperty("value", 1)
        self.spinB_zdc_fine.setObjectName("spinB_zdc_fine")
        self.label_62 = QtWidgets.QLabel(self.page_4)
        self.label_62.setGeometry(QtCore.QRect(80, 140, 68, 19))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.page_4)
        self.label_63.setGeometry(QtCore.QRect(80, 100, 68, 19))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.page_4)
        self.label_64.setGeometry(QtCore.QRect(100, 260, 68, 19))
        self.label_64.setObjectName("label_64")
        self.spinB_zdc_steps_per_rev = QtWidgets.QSpinBox(self.page_4)
        self.spinB_zdc_steps_per_rev.setGeometry(QtCore.QRect(10, 190, 81, 25))
        self.spinB_zdc_steps_per_rev.setMinimum(1)
        self.spinB_zdc_steps_per_rev.setMaximum(51200)
        self.spinB_zdc_steps_per_rev.setProperty("value", 400)
        self.spinB_zdc_steps_per_rev.setObjectName("spinB_zdc_steps_per_rev")
        self.label_65 = QtWidgets.QLabel(self.page_4)
        self.label_65.setGeometry(QtCore.QRect(100, 190, 151, 19))
        self.label_65.setObjectName("label_65")
        self.spinB_zdc_max_RPM = QtWidgets.QSpinBox(self.page_4)
        self.spinB_zdc_max_RPM.setGeometry(QtCore.QRect(10, 260, 81, 25))
        self.spinB_zdc_max_RPM.setMinimum(1)
        self.spinB_zdc_max_RPM.setMaximum(1000)
        self.spinB_zdc_max_RPM.setProperty("value", 120)
        self.spinB_zdc_max_RPM.setObjectName("spinB_zdc_max_RPM")
        self.pushB_zdc_invert = QtWidgets.QPushButton(self.page_4)
        self.pushB_zdc_invert.setGeometry(QtCore.QRect(10, 220, 141, 34))
        self.pushB_zdc_invert.setObjectName("pushB_zdc_invert")
        self.spinB_zdc_coarse = QtWidgets.QSpinBox(self.page_4)
        self.spinB_zdc_coarse.setGeometry(QtCore.QRect(10, 140, 51, 25))
        self.spinB_zdc_coarse.setMinimum(1)
        self.spinB_zdc_coarse.setMaximum(124)
        self.spinB_zdc_coarse.setProperty("value", 10)
        self.spinB_zdc_coarse.setObjectName("spinB_zdc_coarse")
        self.spinB_zdc_mm_per_rev = QtWidgets.QDoubleSpinBox(self.page_4)
        self.spinB_zdc_mm_per_rev.setGeometry(QtCore.QRect(124, 100, 61, 25))
        self.spinB_zdc_mm_per_rev.setProperty("value", 0.5)
        self.spinB_zdc_mm_per_rev.setObjectName("spinB_zdc_mm_per_rev")
        self.label_66 = QtWidgets.QLabel(self.page_4)
        self.label_66.setGeometry(QtCore.QRect(10, 30, 261, 51))
        self.label_66.setObjectName("label_66")
        self.stackedW_settings_leg.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 68, 19))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 68, 19))
        self.label_17.setObjectName("label_17")
        self.label_40 = QtWidgets.QLabel(self.page_2)
        self.label_40.setGeometry(QtCore.QRect(10, 40, 261, 51))
        self.label_40.setObjectName("label_40")
        self.spinB_zbr_fine = QtWidgets.QSpinBox(self.page_2)
        self.spinB_zbr_fine.setGeometry(QtCore.QRect(10, 110, 41, 25))
        self.spinB_zbr_fine.setMinimum(1)
        self.spinB_zbr_fine.setMaximum(32)
        self.spinB_zbr_fine.setProperty("value", 1)
        self.spinB_zbr_fine.setObjectName("spinB_zbr_fine")
        self.spinB_zbr_coarse = QtWidgets.QSpinBox(self.page_2)
        self.spinB_zbr_coarse.setGeometry(QtCore.QRect(10, 150, 51, 25))
        self.spinB_zbr_coarse.setMinimum(1)
        self.spinB_zbr_coarse.setMaximum(124)
        self.spinB_zbr_coarse.setProperty("value", 10)
        self.spinB_zbr_coarse.setObjectName("spinB_zbr_coarse")
        self.label_42 = QtWidgets.QLabel(self.page_2)
        self.label_42.setGeometry(QtCore.QRect(80, 150, 68, 19))
        self.label_42.setObjectName("label_42")
        self.spinB_zbr_steps_per_rev = QtWidgets.QSpinBox(self.page_2)
        self.spinB_zbr_steps_per_rev.setGeometry(QtCore.QRect(10, 200, 81, 25))
        self.spinB_zbr_steps_per_rev.setMinimum(1)
        self.spinB_zbr_steps_per_rev.setMaximum(51200)
        self.spinB_zbr_steps_per_rev.setProperty("value", 400)
        self.spinB_zbr_steps_per_rev.setObjectName("spinB_zbr_steps_per_rev")
        self.spinB_zbr_max_RPM = QtWidgets.QSpinBox(self.page_2)
        self.spinB_zbr_max_RPM.setGeometry(QtCore.QRect(10, 270, 81, 25))
        self.spinB_zbr_max_RPM.setMinimum(1)
        self.spinB_zbr_max_RPM.setMaximum(1000)
        self.spinB_zbr_max_RPM.setProperty("value", 120)
        self.spinB_zbr_max_RPM.setObjectName("spinB_zbr_max_RPM")
        self.pushB_zbr_invert = QtWidgets.QPushButton(self.page_2)
        self.pushB_zbr_invert.setGeometry(QtCore.QRect(10, 230, 131, 34))
        self.pushB_zbr_invert.setObjectName("pushB_zbr_invert")
        self.spinB_zbr_mm_per_rev = QtWidgets.QDoubleSpinBox(self.page_2)
        self.spinB_zbr_mm_per_rev.setGeometry(QtCore.QRect(124, 110, 61, 25))
        self.spinB_zbr_mm_per_rev.setSingleStep(0.0)
        self.spinB_zbr_mm_per_rev.setProperty("value", 0.5)
        self.spinB_zbr_mm_per_rev.setObjectName("spinB_zbr_mm_per_rev")
        self.label_43 = QtWidgets.QLabel(self.page_2)
        self.label_43.setGeometry(QtCore.QRect(100, 200, 151, 19))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.page_2)
        self.label_44.setGeometry(QtCore.QRect(190, 110, 141, 19))
        self.label_44.setObjectName("label_44")
        self.label_41 = QtWidgets.QLabel(self.page_2)
        self.label_41.setGeometry(QtCore.QRect(80, 110, 68, 19))
        self.label_41.setObjectName("label_41")
        self.label_45 = QtWidgets.QLabel(self.page_2)
        self.label_45.setGeometry(QtCore.QRect(100, 270, 68, 19))
        self.label_45.setObjectName("label_45")
        self.stackedW_settings_leg.addWidget(self.page_2)
        self.label_16 = QtWidgets.QLabel(self.legs)
        self.label_16.setGeometry(QtCore.QRect(460, 180, 68, 19))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.legs, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupB_pos_control_x = QtWidgets.QGroupBox(self.tab_2)
        self.groupB_pos_control_x.setGeometry(QtCore.QRect(10, 10, 761, 171))
        self.groupB_pos_control_x.setFlat(True)
        self.groupB_pos_control_x.setCheckable(True)
        self.groupB_pos_control_x.setObjectName("groupB_pos_control_x")
        self.pushB_pos_A = QtWidgets.QPushButton(self.groupB_pos_control_x)
        self.pushB_pos_A.setGeometry(QtCore.QRect(300, 50, 131, 34))
        self.pushB_pos_A.setObjectName("pushB_pos_A")
        self.pushB_pos_B = QtWidgets.QPushButton(self.groupB_pos_control_x)
        self.pushB_pos_B.setGeometry(QtCore.QRect(300, 90, 131, 34))
        self.pushB_pos_B.setObjectName("pushB_pos_B")
        self.lcd_pos_A = QtWidgets.QLCDNumber(self.groupB_pos_control_x)
        self.lcd_pos_A.setGeometry(QtCore.QRect(450, 50, 81, 31))
        self.lcd_pos_A.setProperty("value", 500.0)
        self.lcd_pos_A.setObjectName("lcd_pos_A")
        self.lcd_pos_B = QtWidgets.QLCDNumber(self.groupB_pos_control_x)
        self.lcd_pos_B.setGeometry(QtCore.QRect(450, 90, 81, 31))
        self.lcd_pos_B.setProperty("value", -500.0)
        self.lcd_pos_B.setObjectName("lcd_pos_B")
        self.label_25 = QtWidgets.QLabel(self.groupB_pos_control_x)
        self.label_25.setGeometry(QtCore.QRect(310, 20, 111, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupB_pos_control_x)
        self.label_26.setGeometry(QtCore.QRect(450, 20, 91, 19))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupB_pos_control_x)
        self.label_27.setGeometry(QtCore.QRect(560, 20, 131, 19))
        self.label_27.setObjectName("label_27")
        self.label_overwrite_A = QtWidgets.QLabel(self.groupB_pos_control_x)
        self.label_overwrite_A.setGeometry(QtCore.QRect(580, 50, 68, 31))
        self.label_overwrite_A.setObjectName("label_overwrite_A")
        self.label_overwrite_B = QtWidgets.QLabel(self.groupB_pos_control_x)
        self.label_overwrite_B.setGeometry(QtCore.QRect(580, 90, 68, 31))
        self.label_overwrite_B.setObjectName("label_overwrite_B")
        self.label_2 = QtWidgets.QLabel(self.groupB_pos_control_x)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.label_2.setObjectName("label_2")
        self.dspinB_mm_axis_x = QtWidgets.QDoubleSpinBox(self.groupB_pos_control_x)
        self.dspinB_mm_axis_x.setGeometry(QtCore.QRect(10, 60, 68, 25))
        self.dspinB_mm_axis_x.setProperty("value", 0.5)
        self.dspinB_mm_axis_x.setObjectName("dspinB_mm_axis_x")
        self.spinB_RPM_pos_control_x = QtWidgets.QSpinBox(self.groupB_pos_control_x)
        self.spinB_RPM_pos_control_x.setGeometry(QtCore.QRect(10, 100, 68, 25))
        self.spinB_RPM_pos_control_x.setProperty("value", 30)
        self.spinB_RPM_pos_control_x.setObjectName("spinB_RPM_pos_control_x")
        self.label_3 = QtWidgets.QLabel(self.groupB_pos_control_x)
        self.label_3.setGeometry(QtCore.QRect(90, 100, 68, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupB_pos_control_x)
        self.label_4.setGeometry(QtCore.QRect(90, 60, 91, 19))
        self.label_4.setObjectName("label_4")
        self.pushB_start_x_2 = QtWidgets.QPushButton(self.groupB_pos_control_x)
        self.pushB_start_x_2.setGeometry(QtCore.QRect(210, 50, 51, 41))
        self.pushB_start_x_2.setObjectName("pushB_start_x_2")
        self.pushB_stop_x_2 = QtWidgets.QPushButton(self.groupB_pos_control_x)
        self.pushB_stop_x_2.setGeometry(QtCore.QRect(210, 110, 51, 41))
        self.pushB_stop_x_2.setObjectName("pushB_stop_x_2")
        self.groupB_permanent_x = QtWidgets.QGroupBox(self.tab_2)
        self.groupB_permanent_x.setGeometry(QtCore.QRect(10, 180, 411, 161))
        self.groupB_permanent_x.setFlat(True)
        self.groupB_permanent_x.setCheckable(True)
        self.groupB_permanent_x.setChecked(False)
        self.groupB_permanent_x.setObjectName("groupB_permanent_x")
        self.radioB_forwards_x = QtWidgets.QRadioButton(self.groupB_permanent_x)
        self.radioB_forwards_x.setGeometry(QtCore.QRect(10, 60, 119, 23))
        self.radioB_forwards_x.setChecked(True)
        self.radioB_forwards_x.setObjectName("radioB_forwards_x")
        self.radioB_backwards_x = QtWidgets.QRadioButton(self.groupB_permanent_x)
        self.radioB_backwards_x.setGeometry(QtCore.QRect(10, 90, 119, 23))
        self.radioB_backwards_x.setObjectName("radioB_backwards_x")
        self.pushB_stop_x = QtWidgets.QPushButton(self.groupB_permanent_x)
        self.pushB_stop_x.setGeometry(QtCore.QRect(250, 60, 61, 51))
        self.pushB_stop_x.setObjectName("pushB_stop_x")
        self.spinB_RPM_permanent_x = QtWidgets.QSpinBox(self.groupB_permanent_x)
        self.spinB_RPM_permanent_x.setGeometry(QtCore.QRect(140, 130, 81, 25))
        self.spinB_RPM_permanent_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinB_RPM_permanent_x.setKeyboardTracking(False)
        self.spinB_RPM_permanent_x.setProperty("value", 30)
        self.spinB_RPM_permanent_x.setObjectName("spinB_RPM_permanent_x")
        self.label_28 = QtWidgets.QLabel(self.groupB_permanent_x)
        self.label_28.setGeometry(QtCore.QRect(10, 130, 68, 19))
        self.label_28.setObjectName("label_28")
        self.pushB_start_x = QtWidgets.QPushButton(self.groupB_permanent_x)
        self.pushB_start_x.setGeometry(QtCore.QRect(160, 60, 61, 51))
        self.pushB_start_x.setObjectName("pushB_start_x")
        self.groupB_when_pushed_x = QtWidgets.QGroupBox(self.tab_2)
        self.groupB_when_pushed_x.setGeometry(QtCore.QRect(10, 350, 411, 161))
        self.groupB_when_pushed_x.setFlat(True)
        self.groupB_when_pushed_x.setCheckable(True)
        self.groupB_when_pushed_x.setChecked(False)
        self.groupB_when_pushed_x.setObjectName("groupB_when_pushed_x")
        self.pushB_forwards_x = QtWidgets.QPushButton(self.groupB_when_pushed_x)
        self.pushB_forwards_x.setGeometry(QtCore.QRect(20, 50, 101, 31))
        self.pushB_forwards_x.setAutoRepeat(True)
        self.pushB_forwards_x.setObjectName("pushB_forwards_x")
        self.pushB_backwards_x = QtWidgets.QPushButton(self.groupB_when_pushed_x)
        self.pushB_backwards_x.setGeometry(QtCore.QRect(20, 90, 101, 31))
        self.pushB_backwards_x.setAutoRepeat(True)
        self.pushB_backwards_x.setObjectName("pushB_backwards_x")
        self.label_36 = QtWidgets.QLabel(self.groupB_when_pushed_x)
        self.label_36.setGeometry(QtCore.QRect(140, 50, 68, 19))
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.spinB_RPM_when_pushed_x = QtWidgets.QSpinBox(self.groupB_when_pushed_x)
        self.spinB_RPM_when_pushed_x.setGeometry(QtCore.QRect(150, 130, 81, 25))
        self.spinB_RPM_when_pushed_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinB_RPM_when_pushed_x.setProperty("value", 30)
        self.spinB_RPM_when_pushed_x.setObjectName("spinB_RPM_when_pushed_x")
        self.label_37 = QtWidgets.QLabel(self.groupB_when_pushed_x)
        self.label_37.setGeometry(QtCore.QRect(20, 130, 68, 21))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupB_when_pushed_x)
        self.label_38.setGeometry(QtCore.QRect(150, 50, 161, 71))
        self.label_38.setObjectName("label_38")
        self.groupB_key_control_x = QtWidgets.QGroupBox(self.tab_2)
        self.groupB_key_control_x.setGeometry(QtCore.QRect(10, 520, 751, 91))
        self.groupB_key_control_x.setFlat(True)
        self.groupB_key_control_x.setCheckable(True)
        self.groupB_key_control_x.setChecked(False)
        self.groupB_key_control_x.setObjectName("groupB_key_control_x")
        self.label_39 = QtWidgets.QLabel(self.groupB_key_control_x)
        self.label_39.setGeometry(QtCore.QRect(20, 30, 651, 61))
        self.label_39.setObjectName("label_39")
        self.label_121 = QtWidgets.QLabel(self.tab_2)
        self.label_121.setGeometry(QtCore.QRect(10, 600, 681, 61))
        self.label_121.setObjectName("label_121")
        self.stackedW_settings_x = QtWidgets.QFrame(self.tab_2)
        self.stackedW_settings_x.setGeometry(QtCore.QRect(440, 210, 331, 291))
        self.stackedW_settings_x.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedW_settings_x.setObjectName("stackedW_settings_x")
        self.spinB_x_mm_per_rev = QtWidgets.QDoubleSpinBox(self.stackedW_settings_x)
        self.spinB_x_mm_per_rev.setGeometry(QtCore.QRect(120, 100, 61, 25))
        self.spinB_x_mm_per_rev.setSingleStep(1.0)
        self.spinB_x_mm_per_rev.setProperty("value", 0.5)
        self.spinB_x_mm_per_rev.setObjectName("spinB_x_mm_per_rev")
        self.label_141 = QtWidgets.QLabel(self.stackedW_settings_x)
        self.label_141.setGeometry(QtCore.QRect(80, 100, 68, 19))
        self.label_141.setObjectName("label_141")
        self.spinB_x_fine = QtWidgets.QSpinBox(self.stackedW_settings_x)
        self.spinB_x_fine.setGeometry(QtCore.QRect(10, 100, 41, 25))
        self.spinB_x_fine.setMinimum(1)
        self.spinB_x_fine.setMaximum(32)
        self.spinB_x_fine.setProperty("value", 1)
        self.spinB_x_fine.setObjectName("spinB_x_fine")
        self.label_142 = QtWidgets.QLabel(self.stackedW_settings_x)
        self.label_142.setGeometry(QtCore.QRect(100, 190, 151, 19))
        self.label_142.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_142.setObjectName("label_142")
        self.pushB_x_invert = QtWidgets.QPushButton(self.stackedW_settings_x)
        self.pushB_x_invert.setGeometry(QtCore.QRect(10, 220, 131, 34))
        self.pushB_x_invert.setObjectName("pushB_x_invert")
        self.label_143 = QtWidgets.QLabel(self.stackedW_settings_x)
        self.label_143.setGeometry(QtCore.QRect(80, 140, 68, 19))
        self.label_143.setObjectName("label_143")
        self.spinB_x_coarse = QtWidgets.QSpinBox(self.stackedW_settings_x)
        self.spinB_x_coarse.setGeometry(QtCore.QRect(10, 140, 51, 25))
        self.spinB_x_coarse.setMinimum(1)
        self.spinB_x_coarse.setMaximum(124)
        self.spinB_x_coarse.setProperty("value", 10)
        self.spinB_x_coarse.setObjectName("spinB_x_coarse")
        self.label_144 = QtWidgets.QLabel(self.stackedW_settings_x)
        self.label_144.setGeometry(QtCore.QRect(10, 0, 68, 19))
        self.label_144.setObjectName("label_144")
        self.spinB_x_max_RPM = QtWidgets.QSpinBox(self.stackedW_settings_x)
        self.spinB_x_max_RPM.setGeometry(QtCore.QRect(10, 260, 81, 25))
        self.spinB_x_max_RPM.setMinimum(1)
        self.spinB_x_max_RPM.setMaximum(1000)
        self.spinB_x_max_RPM.setProperty("value", 120)
        self.spinB_x_max_RPM.setObjectName("spinB_x_max_RPM")
        self.label_145 = QtWidgets.QLabel(self.stackedW_settings_x)
        self.label_145.setGeometry(QtCore.QRect(10, 20, 261, 61))
        self.label_145.setObjectName("label_145")
        self.spinB_x_steps_per_rev = QtWidgets.QSpinBox(self.stackedW_settings_x)
        self.spinB_x_steps_per_rev.setGeometry(QtCore.QRect(10, 190, 81, 25))
        self.spinB_x_steps_per_rev.setMinimum(1)
        self.spinB_x_steps_per_rev.setMaximum(51200)
        self.spinB_x_steps_per_rev.setProperty("value", 400)
        self.spinB_x_steps_per_rev.setObjectName("spinB_x_steps_per_rev")
        self.label_146 = QtWidgets.QLabel(self.stackedW_settings_x)
        self.label_146.setGeometry(QtCore.QRect(100, 260, 68, 19))
        self.label_146.setObjectName("label_146")
        self.label_147 = QtWidgets.QLabel(self.stackedW_settings_x)
        self.label_147.setGeometry(QtCore.QRect(190, 100, 151, 19))
        self.label_147.setObjectName("label_147")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(440, 180, 68, 19))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupB_pos_control_pr = QtWidgets.QGroupBox(self.tab_3)
        self.groupB_pos_control_pr.setGeometry(QtCore.QRect(10, 10, 761, 151))
        self.groupB_pos_control_pr.setFlat(True)
        self.groupB_pos_control_pr.setCheckable(True)
        self.groupB_pos_control_pr.setChecked(True)
        self.groupB_pos_control_pr.setObjectName("groupB_pos_control_pr")
        self.pushB_pos_C = QtWidgets.QPushButton(self.groupB_pos_control_pr)
        self.pushB_pos_C.setGeometry(QtCore.QRect(300, 50, 131, 34))
        self.pushB_pos_C.setObjectName("pushB_pos_C")
        self.pushB_pos_D = QtWidgets.QPushButton(self.groupB_pos_control_pr)
        self.pushB_pos_D.setGeometry(QtCore.QRect(300, 90, 131, 34))
        self.pushB_pos_D.setObjectName("pushB_pos_D")
        self.lcd_pos_C = QtWidgets.QLCDNumber(self.groupB_pos_control_pr)
        self.lcd_pos_C.setGeometry(QtCore.QRect(450, 50, 81, 31))
        self.lcd_pos_C.setProperty("value", 15.0)
        self.lcd_pos_C.setObjectName("lcd_pos_C")
        self.lcd_pos_D = QtWidgets.QLCDNumber(self.groupB_pos_control_pr)
        self.lcd_pos_D.setGeometry(QtCore.QRect(450, 90, 81, 31))
        self.lcd_pos_D.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd_pos_D.setProperty("value", -15.0)
        self.lcd_pos_D.setObjectName("lcd_pos_D")
        self.label_148 = QtWidgets.QLabel(self.groupB_pos_control_pr)
        self.label_148.setGeometry(QtCore.QRect(310, 20, 111, 20))
        self.label_148.setObjectName("label_148")
        self.label_149 = QtWidgets.QLabel(self.groupB_pos_control_pr)
        self.label_149.setGeometry(QtCore.QRect(450, 20, 91, 19))
        self.label_149.setObjectName("label_149")
        self.label_150 = QtWidgets.QLabel(self.groupB_pos_control_pr)
        self.label_150.setGeometry(QtCore.QRect(560, 20, 131, 19))
        self.label_150.setObjectName("label_150")
        self.label_overwrite_C = QtWidgets.QLabel(self.groupB_pos_control_pr)
        self.label_overwrite_C.setGeometry(QtCore.QRect(580, 50, 68, 31))
        self.label_overwrite_C.setObjectName("label_overwrite_C")
        self.label_overwrite_D = QtWidgets.QLabel(self.groupB_pos_control_pr)
        self.label_overwrite_D.setGeometry(QtCore.QRect(580, 90, 68, 31))
        self.label_overwrite_D.setObjectName("label_overwrite_D")
        self.label_5 = QtWidgets.QLabel(self.groupB_pos_control_pr)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.label_5.setObjectName("label_5")
        self.dspinBox_deg_on_axis_pr = QtWidgets.QDoubleSpinBox(self.groupB_pos_control_pr)
        self.dspinBox_deg_on_axis_pr.setGeometry(QtCore.QRect(10, 60, 68, 25))
        self.dspinBox_deg_on_axis_pr.setMaximum(180.0)
        self.dspinBox_deg_on_axis_pr.setSingleStep(1.0)
        self.dspinBox_deg_on_axis_pr.setProperty("value", 30.0)
        self.dspinBox_deg_on_axis_pr.setObjectName("dspinBox_deg_on_axis_pr")
        self.spinB_RPM_pr_pos_control = QtWidgets.QSpinBox(self.groupB_pos_control_pr)
        self.spinB_RPM_pr_pos_control.setGeometry(QtCore.QRect(10, 100, 68, 25))
        self.spinB_RPM_pr_pos_control.setProperty("value", 30)
        self.spinB_RPM_pr_pos_control.setObjectName("spinB_RPM_pr_pos_control")
        self.label_6 = QtWidgets.QLabel(self.groupB_pos_control_pr)
        self.label_6.setGeometry(QtCore.QRect(90, 100, 68, 19))
        self.label_6.setObjectName("label_6")
        self.label_151 = QtWidgets.QLabel(self.groupB_pos_control_pr)
        self.label_151.setGeometry(QtCore.QRect(90, 60, 91, 19))
        self.label_151.setObjectName("label_151")
        self.pushB_start_PR = QtWidgets.QPushButton(self.groupB_pos_control_pr)
        self.pushB_start_PR.setGeometry(QtCore.QRect(210, 50, 51, 41))
        self.pushB_start_PR.setObjectName("pushB_start_PR")
        self.pushB_stop_PR = QtWidgets.QPushButton(self.groupB_pos_control_pr)
        self.pushB_stop_PR.setGeometry(QtCore.QRect(210, 100, 51, 41))
        self.pushB_stop_PR.setObjectName("pushB_stop_PR")
        self.groupB_when_pushed_pr = QtWidgets.QGroupBox(self.tab_3)
        self.groupB_when_pushed_pr.setGeometry(QtCore.QRect(10, 180, 411, 161))
        self.groupB_when_pushed_pr.setFlat(True)
        self.groupB_when_pushed_pr.setCheckable(True)
        self.groupB_when_pushed_pr.setChecked(False)
        self.groupB_when_pushed_pr.setObjectName("groupB_when_pushed_pr")
        self.pushB_lefthand = QtWidgets.QPushButton(self.groupB_when_pushed_pr)
        self.pushB_lefthand.setGeometry(QtCore.QRect(20, 50, 101, 31))
        self.pushB_lefthand.setAutoRepeat(True)
        self.pushB_lefthand.setObjectName("pushB_lefthand")
        self.pushB_righthand = QtWidgets.QPushButton(self.groupB_when_pushed_pr)
        self.pushB_righthand.setGeometry(QtCore.QRect(20, 90, 101, 31))
        self.pushB_righthand.setAutoRepeat(True)
        self.pushB_righthand.setObjectName("pushB_righthand")
        self.label_152 = QtWidgets.QLabel(self.groupB_when_pushed_pr)
        self.label_152.setGeometry(QtCore.QRect(140, 50, 68, 19))
        self.label_152.setText("")
        self.label_152.setObjectName("label_152")
        self.spinB_RPM_when_pushed_pr = QtWidgets.QSpinBox(self.groupB_when_pushed_pr)
        self.spinB_RPM_when_pushed_pr.setGeometry(QtCore.QRect(150, 130, 81, 25))
        self.spinB_RPM_when_pushed_pr.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinB_RPM_when_pushed_pr.setProperty("value", 30)
        self.spinB_RPM_when_pushed_pr.setObjectName("spinB_RPM_when_pushed_pr")
        self.label_153 = QtWidgets.QLabel(self.groupB_when_pushed_pr)
        self.label_153.setGeometry(QtCore.QRect(20, 130, 68, 21))
        self.label_153.setObjectName("label_153")
        self.label_154 = QtWidgets.QLabel(self.groupB_when_pushed_pr)
        self.label_154.setGeometry(QtCore.QRect(150, 50, 161, 71))
        self.label_154.setObjectName("label_154")
        self.groupB_key_control_pr = QtWidgets.QGroupBox(self.tab_3)
        self.groupB_key_control_pr.setGeometry(QtCore.QRect(10, 350, 411, 141))
        self.groupB_key_control_pr.setFlat(True)
        self.groupB_key_control_pr.setCheckable(True)
        self.groupB_key_control_pr.setChecked(False)
        self.groupB_key_control_pr.setObjectName("groupB_key_control_pr")
        self.label_155 = QtWidgets.QLabel(self.groupB_key_control_pr)
        self.label_155.setGeometry(QtCore.QRect(20, 50, 371, 61))
        self.label_155.setObjectName("label_155")
        self.label_163 = QtWidgets.QLabel(self.tab_3)
        self.label_163.setGeometry(QtCore.QRect(440, 180, 68, 19))
        self.label_163.setObjectName("label_163")
        self.stackedW_settings_pr_cr = QtWidgets.QStackedWidget(self.tab_3)
        self.stackedW_settings_pr_cr.setGeometry(QtCore.QRect(440, 200, 331, 301))
        self.stackedW_settings_pr_cr.setObjectName("stackedW_settings_pr_cr")
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.label_178 = QtWidgets.QLabel(self.page_16)
        self.label_178.setGeometry(QtCore.QRect(10, 10, 68, 19))
        self.label_178.setText("")
        self.label_178.setObjectName("label_178")
        self.label_179 = QtWidgets.QLabel(self.page_16)
        self.label_179.setGeometry(QtCore.QRect(10, 10, 68, 19))
        self.label_179.setObjectName("label_179")
        self.label_180 = QtWidgets.QLabel(self.page_16)
        self.label_180.setGeometry(QtCore.QRect(10, 30, 261, 61))
        self.label_180.setObjectName("label_180")
        self.spinB_pr_fine = QtWidgets.QSpinBox(self.page_16)
        self.spinB_pr_fine.setGeometry(QtCore.QRect(10, 110, 41, 25))
        self.spinB_pr_fine.setMinimum(1)
        self.spinB_pr_fine.setMaximum(32)
        self.spinB_pr_fine.setProperty("value", 1)
        self.spinB_pr_fine.setObjectName("spinB_pr_fine")
        self.spinB_pr_coarse = QtWidgets.QSpinBox(self.page_16)
        self.spinB_pr_coarse.setGeometry(QtCore.QRect(10, 150, 51, 25))
        self.spinB_pr_coarse.setMinimum(1)
        self.spinB_pr_coarse.setMaximum(124)
        self.spinB_pr_coarse.setProperty("value", 10)
        self.spinB_pr_coarse.setObjectName("spinB_pr_coarse")
        self.label_181 = QtWidgets.QLabel(self.page_16)
        self.label_181.setGeometry(QtCore.QRect(80, 150, 68, 19))
        self.label_181.setObjectName("label_181")
        self.spinB_pr_steps_per_rev = QtWidgets.QSpinBox(self.page_16)
        self.spinB_pr_steps_per_rev.setGeometry(QtCore.QRect(10, 200, 81, 25))
        self.spinB_pr_steps_per_rev.setMinimum(1)
        self.spinB_pr_steps_per_rev.setMaximum(51200)
        self.spinB_pr_steps_per_rev.setProperty("value", 400)
        self.spinB_pr_steps_per_rev.setObjectName("spinB_pr_steps_per_rev")
        self.spinB_pr_max_RPM = QtWidgets.QSpinBox(self.page_16)
        self.spinB_pr_max_RPM.setGeometry(QtCore.QRect(10, 270, 81, 25))
        self.spinB_pr_max_RPM.setMinimum(-1)
        self.spinB_pr_max_RPM.setMaximum(1000)
        self.spinB_pr_max_RPM.setProperty("value", 120)
        self.spinB_pr_max_RPM.setObjectName("spinB_pr_max_RPM")
        self.pushB_pr_invert = QtWidgets.QPushButton(self.page_16)
        self.pushB_pr_invert.setGeometry(QtCore.QRect(10, 230, 131, 34))
        self.pushB_pr_invert.setObjectName("pushB_pr_invert")
        self.spinB_pr_mm_per_rev = QtWidgets.QDoubleSpinBox(self.page_16)
        self.spinB_pr_mm_per_rev.setGeometry(QtCore.QRect(124, 110, 61, 25))
        self.spinB_pr_mm_per_rev.setProperty("value", 0.5)
        self.spinB_pr_mm_per_rev.setObjectName("spinB_pr_mm_per_rev")
        self.label_182 = QtWidgets.QLabel(self.page_16)
        self.label_182.setGeometry(QtCore.QRect(100, 200, 151, 19))
        self.label_182.setObjectName("label_182")
        self.label_183 = QtWidgets.QLabel(self.page_16)
        self.label_183.setGeometry(QtCore.QRect(190, 110, 141, 19))
        self.label_183.setObjectName("label_183")
        self.label_184 = QtWidgets.QLabel(self.page_16)
        self.label_184.setGeometry(QtCore.QRect(80, 110, 68, 19))
        self.label_184.setObjectName("label_184")
        self.label_185 = QtWidgets.QLabel(self.page_16)
        self.label_185.setGeometry(QtCore.QRect(100, 270, 68, 19))
        self.label_185.setObjectName("label_185")
        self.stackedW_settings_pr_cr.addWidget(self.page_16)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.spinB_cr_mm_per_rev = QtWidgets.QDoubleSpinBox(self.page_13)
        self.spinB_cr_mm_per_rev.setGeometry(QtCore.QRect(124, 110, 61, 25))
        self.spinB_cr_mm_per_rev.setSingleStep(1.0)
        self.spinB_cr_mm_per_rev.setProperty("value", 0.5)
        self.spinB_cr_mm_per_rev.setObjectName("spinB_cr_mm_per_rev")
        self.spinB_cr_fine = QtWidgets.QSpinBox(self.page_13)
        self.spinB_cr_fine.setGeometry(QtCore.QRect(10, 110, 41, 25))
        self.spinB_cr_fine.setMinimum(1)
        self.spinB_cr_fine.setMaximum(32)
        self.spinB_cr_fine.setObjectName("spinB_cr_fine")
        self.spinB_cr_steps_per_rev = QtWidgets.QSpinBox(self.page_13)
        self.spinB_cr_steps_per_rev.setGeometry(QtCore.QRect(10, 200, 81, 25))
        self.spinB_cr_steps_per_rev.setMinimum(1)
        self.spinB_cr_steps_per_rev.setMaximum(51200)
        self.spinB_cr_steps_per_rev.setProperty("value", 400)
        self.spinB_cr_steps_per_rev.setObjectName("spinB_cr_steps_per_rev")
        self.spinB_cr_max_RPM = QtWidgets.QSpinBox(self.page_13)
        self.spinB_cr_max_RPM.setGeometry(QtCore.QRect(10, 270, 81, 25))
        self.spinB_cr_max_RPM.setMinimum(1)
        self.spinB_cr_max_RPM.setMaximum(1000)
        self.spinB_cr_max_RPM.setProperty("value", 120)
        self.spinB_cr_max_RPM.setObjectName("spinB_cr_max_RPM")
        self.spinB_cr_coarse = QtWidgets.QSpinBox(self.page_13)
        self.spinB_cr_coarse.setGeometry(QtCore.QRect(10, 150, 51, 25))
        self.spinB_cr_coarse.setMinimum(1)
        self.spinB_cr_coarse.setMaximum(124)
        self.spinB_cr_coarse.setProperty("value", 10)
        self.spinB_cr_coarse.setObjectName("spinB_cr_coarse")
        self.pushB_cr_invert = QtWidgets.QPushButton(self.page_13)
        self.pushB_cr_invert.setGeometry(QtCore.QRect(10, 230, 131, 34))
        self.pushB_cr_invert.setObjectName("pushB_cr_invert")
        self.label_186 = QtWidgets.QLabel(self.page_13)
        self.label_186.setGeometry(QtCore.QRect(100, 270, 68, 19))
        self.label_186.setObjectName("label_186")
        self.label_187 = QtWidgets.QLabel(self.page_13)
        self.label_187.setGeometry(QtCore.QRect(190, 110, 141, 19))
        self.label_187.setObjectName("label_187")
        self.label_188 = QtWidgets.QLabel(self.page_13)
        self.label_188.setGeometry(QtCore.QRect(80, 150, 68, 19))
        self.label_188.setObjectName("label_188")
        self.label_189 = QtWidgets.QLabel(self.page_13)
        self.label_189.setGeometry(QtCore.QRect(10, 30, 261, 61))
        self.label_189.setObjectName("label_189")
        self.label_190 = QtWidgets.QLabel(self.page_13)
        self.label_190.setGeometry(QtCore.QRect(100, 200, 151, 19))
        self.label_190.setObjectName("label_190")
        self.label_191 = QtWidgets.QLabel(self.page_13)
        self.label_191.setGeometry(QtCore.QRect(80, 110, 68, 19))
        self.label_191.setObjectName("label_191")
        self.label_156 = QtWidgets.QLabel(self.page_13)
        self.label_156.setGeometry(QtCore.QRect(10, 10, 68, 19))
        self.label_156.setObjectName("label_156")
        self.stackedW_settings_pr_cr.addWidget(self.page_13)
        self.groupB_pos_control_cr = QtWidgets.QGroupBox(self.tab_3)
        self.groupB_pos_control_cr.setGeometry(QtCore.QRect(10, 510, 411, 161))
        self.groupB_pos_control_cr.setFlat(True)
        self.groupB_pos_control_cr.setCheckable(True)
        self.groupB_pos_control_cr.setChecked(True)
        self.groupB_pos_control_cr.setObjectName("groupB_pos_control_cr")
        self.pushB_pos_raman = QtWidgets.QPushButton(self.groupB_pos_control_cr)
        self.pushB_pos_raman.setGeometry(QtCore.QRect(10, 60, 131, 34))
        self.pushB_pos_raman.setObjectName("pushB_pos_raman")
        self.pushB_pos_ion_beam = QtWidgets.QPushButton(self.groupB_pos_control_cr)
        self.pushB_pos_ion_beam.setGeometry(QtCore.QRect(10, 100, 131, 34))
        self.pushB_pos_ion_beam.setObjectName("pushB_pos_ion_beam")
        self.lcd_pos_raman = QtWidgets.QLCDNumber(self.groupB_pos_control_cr)
        self.lcd_pos_raman.setGeometry(QtCore.QRect(170, 60, 81, 31))
        self.lcd_pos_raman.setProperty("value", 90.0)
        self.lcd_pos_raman.setObjectName("lcd_pos_raman")
        self.lcd_pos_ion_beam = QtWidgets.QLCDNumber(self.groupB_pos_control_cr)
        self.lcd_pos_ion_beam.setGeometry(QtCore.QRect(170, 100, 81, 31))
        self.lcd_pos_ion_beam.setObjectName("lcd_pos_ion_beam")
        self.label_157 = QtWidgets.QLabel(self.groupB_pos_control_cr)
        self.label_157.setGeometry(QtCore.QRect(20, 30, 111, 20))
        self.label_157.setObjectName("label_157")
        self.label_158 = QtWidgets.QLabel(self.groupB_pos_control_cr)
        self.label_158.setGeometry(QtCore.QRect(170, 30, 91, 19))
        self.label_158.setObjectName("label_158")
        self.label_159 = QtWidgets.QLabel(self.groupB_pos_control_cr)
        self.label_159.setGeometry(QtCore.QRect(270, 30, 131, 19))
        self.label_159.setObjectName("label_159")
        self.label_overwrite_raman = QtWidgets.QLabel(self.groupB_pos_control_cr)
        self.label_overwrite_raman.setGeometry(QtCore.QRect(290, 60, 68, 31))
        self.label_overwrite_raman.setObjectName("label_overwrite_raman")
        self.label_overwrite_ion_beam = QtWidgets.QLabel(self.groupB_pos_control_cr)
        self.label_overwrite_ion_beam.setGeometry(QtCore.QRect(290, 100, 68, 31))
        self.label_overwrite_ion_beam.setObjectName("label_overwrite_ion_beam")
        self.groupB_key_control_cr = QtWidgets.QGroupBox(self.tab_3)
        self.groupB_key_control_cr.setGeometry(QtCore.QRect(440, 510, 331, 131))
        self.groupB_key_control_cr.setFlat(True)
        self.groupB_key_control_cr.setCheckable(True)
        self.groupB_key_control_cr.setChecked(False)
        self.groupB_key_control_cr.setObjectName("groupB_key_control_cr")
        self.label_160 = QtWidgets.QLabel(self.groupB_key_control_cr)
        self.label_160.setGeometry(QtCore.QRect(50, 40, 211, 91))
        self.label_160.setObjectName("label_160")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_162 = QtWidgets.QLabel(self.tab)
        self.label_162.setGeometry(QtCore.QRect(10, 80, 68, 19))
        self.label_162.setText("")
        self.label_162.setObjectName("label_162")
        self.stackedW_settings_s = QtWidgets.QFrame(self.tab)
        self.stackedW_settings_s.setGeometry(QtCore.QRect(0, 140, 331, 291))
        self.stackedW_settings_s.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedW_settings_s.setObjectName("stackedW_settings_s")
        self.spinB_s_mm_per_rev = QtWidgets.QDoubleSpinBox(self.stackedW_settings_s)
        self.spinB_s_mm_per_rev.setGeometry(QtCore.QRect(120, 100, 61, 25))
        self.spinB_s_mm_per_rev.setSingleStep(1.0)
        self.spinB_s_mm_per_rev.setProperty("value", 0.5)
        self.spinB_s_mm_per_rev.setObjectName("spinB_s_mm_per_rev")
        self.label_170 = QtWidgets.QLabel(self.stackedW_settings_s)
        self.label_170.setGeometry(QtCore.QRect(80, 100, 68, 19))
        self.label_170.setObjectName("label_170")
        self.spinB_s_fine = QtWidgets.QSpinBox(self.stackedW_settings_s)
        self.spinB_s_fine.setGeometry(QtCore.QRect(10, 100, 41, 25))
        self.spinB_s_fine.setMinimum(1)
        self.spinB_s_fine.setMaximum(32)
        self.spinB_s_fine.setObjectName("spinB_s_fine")
        self.label_171 = QtWidgets.QLabel(self.stackedW_settings_s)
        self.label_171.setGeometry(QtCore.QRect(100, 190, 151, 19))
        self.label_171.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_171.setObjectName("label_171")
        self.pushB_s_invert = QtWidgets.QPushButton(self.stackedW_settings_s)
        self.pushB_s_invert.setGeometry(QtCore.QRect(10, 220, 131, 34))
        self.pushB_s_invert.setObjectName("pushB_s_invert")
        self.label_172 = QtWidgets.QLabel(self.stackedW_settings_s)
        self.label_172.setGeometry(QtCore.QRect(80, 140, 68, 19))
        self.label_172.setObjectName("label_172")
        self.spinB_s_coarse = QtWidgets.QSpinBox(self.stackedW_settings_s)
        self.spinB_s_coarse.setGeometry(QtCore.QRect(10, 140, 51, 25))
        self.spinB_s_coarse.setMinimum(1)
        self.spinB_s_coarse.setMaximum(124)
        self.spinB_s_coarse.setProperty("value", 10)
        self.spinB_s_coarse.setObjectName("spinB_s_coarse")
        self.label_173 = QtWidgets.QLabel(self.stackedW_settings_s)
        self.label_173.setGeometry(QtCore.QRect(10, 0, 68, 19))
        self.label_173.setObjectName("label_173")
        self.spinB_s_max_RPM = QtWidgets.QSpinBox(self.stackedW_settings_s)
        self.spinB_s_max_RPM.setGeometry(QtCore.QRect(10, 260, 81, 25))
        self.spinB_s_max_RPM.setMaximum(1000)
        self.spinB_s_max_RPM.setProperty("value", 120)
        self.spinB_s_max_RPM.setObjectName("spinB_s_max_RPM")
        self.label_174 = QtWidgets.QLabel(self.stackedW_settings_s)
        self.label_174.setGeometry(QtCore.QRect(10, 20, 261, 61))
        self.label_174.setObjectName("label_174")
        self.spinB_s_steps_per_rev = QtWidgets.QSpinBox(self.stackedW_settings_s)
        self.spinB_s_steps_per_rev.setGeometry(QtCore.QRect(10, 190, 81, 25))
        self.spinB_s_steps_per_rev.setMaximum(51200)
        self.spinB_s_steps_per_rev.setProperty("value", 400)
        self.spinB_s_steps_per_rev.setObjectName("spinB_s_steps_per_rev")
        self.label_175 = QtWidgets.QLabel(self.stackedW_settings_s)
        self.label_175.setGeometry(QtCore.QRect(100, 260, 68, 19))
        self.label_175.setObjectName("label_175")
        self.label_176 = QtWidgets.QLabel(self.stackedW_settings_s)
        self.label_176.setGeometry(QtCore.QRect(190, 100, 151, 19))
        self.label_176.setObjectName("label_176")
        self.groupB_key_control_switch = QtWidgets.QGroupBox(self.tab)
        self.groupB_key_control_switch.setGeometry(QtCore.QRect(200, 10, 571, 121))
        self.groupB_key_control_switch.setFlat(True)
        self.groupB_key_control_switch.setCheckable(True)
        self.groupB_key_control_switch.setChecked(False)
        self.groupB_key_control_switch.setObjectName("groupB_key_control_switch")
        self.label_177 = QtWidgets.QLabel(self.groupB_key_control_switch)
        self.label_177.setGeometry(QtCore.QRect(20, 40, 371, 61))
        self.label_177.setObjectName("label_177")
        self.groupB_switch = QtWidgets.QGroupBox(self.tab)
        self.groupB_switch.setGeometry(QtCore.QRect(10, 10, 181, 131))
        self.groupB_switch.setFlat(True)
        self.groupB_switch.setCheckable(True)
        self.groupB_switch.setChecked(True)
        self.groupB_switch.setObjectName("groupB_switch")
        self.pushB_switch = QtWidgets.QPushButton(self.groupB_switch)
        self.pushB_switch.setGeometry(QtCore.QRect(10, 50, 121, 34))
        self.pushB_switch.setObjectName("pushB_switch")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedW_settings_leg.setCurrentIndex(1)
        self.stackedW_settings_pr_cr.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Motor connection"))
        self.groupB_mselection_leg.setTitle(_translate("MainWindow", "Motor selection and position "))
        self.radioB_all_motors.setText(_translate("MainWindow", "all leg motors "))
        self.radioB_single_motor.setText(_translate("MainWindow", "single leg motor"))
        self.checkB_zbr.setText(_translate("MainWindow", "ZBR"))
        self.checkB_zbc.setText(_translate("MainWindow", "ZBC"))
        self.checkB_zdr.setText(_translate("MainWindow", "ZDR"))
        self.checkB_zdc.setText(_translate("MainWindow", "ZDC"))
        self.pushB_pos_up.setText(_translate("MainWindow", "all the way up"))
        self.pushB_pos_down.setText(_translate("MainWindow", "all the way down"))
        self.label_7.setText(_translate("MainWindow", "saved positions"))
        self.label_8.setText(_translate("MainWindow", "mm on axis"))
        self.label_9.setText(_translate("MainWindow", "overwrite Position"))
        self.label_overwrite_up.setText(_translate("MainWindow", "Ctrl + U"))
        self.label_overwrite_down.setText(_translate("MainWindow", "Ctrl + D"))
        self.groupB_when_pushed_leg.setTitle(_translate("MainWindow", "When pushed"))
        self.pushB_forwards_leg.setText(_translate("MainWindow", "forwards"))
        self.pushB_backwards_leg.setText(_translate("MainWindow", "backwards"))
        self.label_11.setText(_translate("MainWindow", "RPM"))
        self.label_12.setText(_translate("MainWindow", "Takes steps as long as \n"
"button pressed"))
        self.groupB_permanent_leg.setTitle(_translate("MainWindow", "Permanent"))
        self.radioB_forwards_leg.setText(_translate("MainWindow", "forwards "))
        self.radioB_backwards_leg.setText(_translate("MainWindow", "backwards "))
        self.pushB_stop_leg.setText(_translate("MainWindow", "Stop"))
        self.label_13.setText(_translate("MainWindow", "RPM"))
        self.pushB_start_leg.setText(_translate("MainWindow", "Start"))
        self.groupB_key_control_leg.setTitle(_translate("MainWindow", "Keyboard control"))
        self.label_21.setText(_translate("MainWindow", "Used for small adjustments. \n"
"Click / hold arrow keys for defined motion motion distance. \n"
"For details check setting page. "))
        self.label_14.setText(_translate("MainWindow", "Info: \n"
"-usually 30 - 120 RPM is a good choice. At higher RPM, torque decreases."))
        self.label_46.setText(_translate("MainWindow", "fine"))
        self.label_47.setText(_translate("MainWindow", "steps per revolutions"))
        self.pushB_zbc_invert.setText(_translate("MainWindow", "invert direction"))
        self.label_48.setText(_translate("MainWindow", "coarse"))
        self.label_49.setText(_translate("MainWindow", "ZBC"))
        self.label_50.setText(_translate("MainWindow", "keyboard controls:\n"
"press up and down for fine steps\n"
" left and right for coarse steps"))
        self.label_51.setText(_translate("MainWindow", "max RPM"))
        self.label_52.setText(_translate("MainWindow", "mm per Revolution"))
        self.label_53.setText(_translate("MainWindow", "mm per Revolution"))
        self.label_54.setText(_translate("MainWindow", "ZDR"))
        self.label_55.setText(_translate("MainWindow", "coarse"))
        self.label_56.setText(_translate("MainWindow", "fine"))
        self.label_57.setText(_translate("MainWindow", "max RPM"))
        self.label_58.setText(_translate("MainWindow", "steps per revolutions"))
        self.pushB_zdr_invert.setText(_translate("MainWindow", "invert direction"))
        self.label_59.setText(_translate("MainWindow", "keyboard controls:\n"
"press up and down for fine steps\n"
" left and right for coarse steps"))
        self.label_60.setText(_translate("MainWindow", "mm per Revolution"))
        self.label_61.setText(_translate("MainWindow", "ZDC"))
        self.label_62.setText(_translate("MainWindow", "coarse"))
        self.label_63.setText(_translate("MainWindow", "fine"))
        self.label_64.setText(_translate("MainWindow", "max RPM"))
        self.label_65.setText(_translate("MainWindow", "steps per revolutions"))
        self.pushB_zdc_invert.setText(_translate("MainWindow", "invert direction"))
        self.label_66.setText(_translate("MainWindow", "keyboard controls:\n"
"press up and down for fine steps\n"
" left and right for coarse steps"))
        self.label_17.setText(_translate("MainWindow", "ZBR"))
        self.label_40.setText(_translate("MainWindow", "keyboard controls:\n"
"press up and down for fine steps\n"
" left and right for coarse steps"))
        self.label_42.setText(_translate("MainWindow", "coarse"))
        self.pushB_zbr_invert.setText(_translate("MainWindow", "invert direction"))
        self.label_43.setText(_translate("MainWindow", "steps per Revolution"))
        self.label_44.setText(_translate("MainWindow", "mm per Revolution"))
        self.label_41.setText(_translate("MainWindow", "fine"))
        self.label_45.setText(_translate("MainWindow", "max RPM"))
        self.label_16.setText(_translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.legs), _translate("MainWindow", "Leg control"))
        self.groupB_pos_control_x.setTitle(_translate("MainWindow", "Position control "))
        self.pushB_pos_A.setText(_translate("MainWindow", "Position A"))
        self.pushB_pos_B.setText(_translate("MainWindow", "Position B"))
        self.label_25.setText(_translate("MainWindow", "saved positions"))
        self.label_26.setText(_translate("MainWindow", "mm on axis"))
        self.label_27.setText(_translate("MainWindow", "overwrite Position"))
        self.label_overwrite_A.setText(_translate("MainWindow", "Ctrl + A"))
        self.label_overwrite_B.setText(_translate("MainWindow", "Ctrl + B"))
        self.label_2.setText(_translate("MainWindow", "absolut Position"))
        self.label_3.setText(_translate("MainWindow", "RPM"))
        self.label_4.setText(_translate("MainWindow", "mm on axis"))
        self.pushB_start_x_2.setText(_translate("MainWindow", "Start"))
        self.pushB_stop_x_2.setText(_translate("MainWindow", "Stop"))
        self.groupB_permanent_x.setTitle(_translate("MainWindow", "Permanent"))
        self.radioB_forwards_x.setText(_translate("MainWindow", "forwards "))
        self.radioB_backwards_x.setText(_translate("MainWindow", "backwards "))
        self.pushB_stop_x.setText(_translate("MainWindow", "Stop"))
        self.label_28.setText(_translate("MainWindow", "RPM"))
        self.pushB_start_x.setText(_translate("MainWindow", "Start"))
        self.groupB_when_pushed_x.setTitle(_translate("MainWindow", "When pushed"))
        self.pushB_forwards_x.setText(_translate("MainWindow", "forwards"))
        self.pushB_backwards_x.setText(_translate("MainWindow", "backwards"))
        self.label_37.setText(_translate("MainWindow", "RPM"))
        self.label_38.setText(_translate("MainWindow", "Takes steps as long as \n"
"button pressed"))
        self.groupB_key_control_x.setTitle(_translate("MainWindow", " Keyboard control"))
        self.label_39.setText(_translate("MainWindow", "Used for small adjustments. \n"
"Click / hold arrow keys for defined motion motion distance. \n"
"For details check setting page. "))
        self.label_121.setText(_translate("MainWindow", "Info: \n"
"-usually 30 - 120 RPM is a good choice. At higher RPM, torque decreases."))
        self.label_141.setText(_translate("MainWindow", "fine"))
        self.label_142.setText(_translate("MainWindow", "steps per revolutions"))
        self.pushB_x_invert.setText(_translate("MainWindow", "invert direction"))
        self.label_143.setText(_translate("MainWindow", "coarse"))
        self.label_144.setText(_translate("MainWindow", "X:"))
        self.label_145.setText(_translate("MainWindow", "keyboard controls:\n"
"press up and down for fine steps\n"
"left and right for coarse steps"))
        self.label_146.setText(_translate("MainWindow", "max RPM"))
        self.label_147.setText(_translate("MainWindow", "mm per Revolution"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "X direction"))
        self.groupB_pos_control_pr.setTitle(_translate("MainWindow", " PR position control "))
        self.pushB_pos_C.setText(_translate("MainWindow", "Position C"))
        self.pushB_pos_D.setText(_translate("MainWindow", "Position D"))
        self.label_148.setText(_translate("MainWindow", "saved positions"))
        self.label_149.setText(_translate("MainWindow", "deg on axis"))
        self.label_150.setText(_translate("MainWindow", "overwrite Position"))
        self.label_overwrite_C.setText(_translate("MainWindow", "Ctrl + C"))
        self.label_overwrite_D.setText(_translate("MainWindow", "Ctrl + D"))
        self.label_5.setText(_translate("MainWindow", "absolut Position"))
        self.label_6.setText(_translate("MainWindow", "RPM"))
        self.label_151.setText(_translate("MainWindow", "deg on axis"))
        self.pushB_start_PR.setText(_translate("MainWindow", "Start"))
        self.pushB_stop_PR.setText(_translate("MainWindow", "Stop"))
        self.groupB_when_pushed_pr.setTitle(_translate("MainWindow", "PR when pushed"))
        self.pushB_lefthand.setText(_translate("MainWindow", "lefthand"))
        self.pushB_righthand.setText(_translate("MainWindow", "righthand"))
        self.label_153.setText(_translate("MainWindow", "RPM"))
        self.label_154.setText(_translate("MainWindow", "Takes steps as long as \n"
"button pressed"))
        self.groupB_key_control_pr.setTitle(_translate("MainWindow", " PR keyboard control"))
        self.label_155.setText(_translate("MainWindow", "Used for small adjustments. \n"
"Click / hold arrow keys for defined motion distance. \n"
"For details check setting page. "))
        self.label_163.setText(_translate("MainWindow", "Settings"))
        self.label_179.setText(_translate("MainWindow", "PR:"))
        self.label_180.setText(_translate("MainWindow", "keyboard controls:\n"
"press up and down for fine steps\n"
"left and right for coarse steps"))
        self.label_181.setText(_translate("MainWindow", "coarse"))
        self.pushB_pr_invert.setText(_translate("MainWindow", "invert direction"))
        self.label_182.setText(_translate("MainWindow", "steps per Revolution"))
        self.label_183.setText(_translate("MainWindow", "deg per Revolution"))
        self.label_184.setText(_translate("MainWindow", "fine"))
        self.label_185.setText(_translate("MainWindow", "max RPM"))
        self.pushB_cr_invert.setText(_translate("MainWindow", "invert direction"))
        self.label_186.setText(_translate("MainWindow", "max RPM"))
        self.label_187.setText(_translate("MainWindow", "deg per Revolution"))
        self.label_188.setText(_translate("MainWindow", "coarse"))
        self.label_189.setText(_translate("MainWindow", "keyboard controls:\n"
"press up and down for fine steps\n"
"left and right for coarse steps"))
        self.label_190.setText(_translate("MainWindow", "steps per Revolution"))
        self.label_191.setText(_translate("MainWindow", "fine"))
        self.label_156.setText(_translate("MainWindow", "CR:"))
        self.groupB_pos_control_cr.setTitle(_translate("MainWindow", "CR position control "))
        self.pushB_pos_raman.setText(_translate("MainWindow", "raman "))
        self.pushB_pos_ion_beam.setText(_translate("MainWindow", "ion beam "))
        self.label_157.setText(_translate("MainWindow", "saved positions"))
        self.label_158.setText(_translate("MainWindow", "deg on axis"))
        self.label_159.setText(_translate("MainWindow", "overwrite Position"))
        self.label_overwrite_raman.setText(_translate("MainWindow", "Ctrl + R"))
        self.label_overwrite_ion_beam.setText(_translate("MainWindow", "Ctrl + I"))
        self.groupB_key_control_cr.setTitle(_translate("MainWindow", " CR keyboard control"))
        self.label_160.setText(_translate("MainWindow", "Used for small adjustments. \n"
"Click / hold arrow keys for\n"
"defined motion distance. \n"
"For details check setting page. "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "PR / CR"))
        self.label_170.setText(_translate("MainWindow", "fine"))
        self.label_171.setText(_translate("MainWindow", "steps per revolutions"))
        self.pushB_s_invert.setText(_translate("MainWindow", "invert direction"))
        self.label_172.setText(_translate("MainWindow", "coarse"))
        self.label_173.setText(_translate("MainWindow", "S:"))
        self.label_174.setText(_translate("MainWindow", "keyboard controls:\n"
"press up and down for fine steps\n"
"left and right for coarse steps"))
        self.label_175.setText(_translate("MainWindow", "max RPM"))
        self.label_176.setText(_translate("MainWindow", "mm per Revolution"))
        self.groupB_key_control_switch.setTitle(_translate("MainWindow", " PR keyboard control"))
        self.label_177.setText(_translate("MainWindow", "Use carefully if specimen wasn\'t switched properly. \n"
"Click / hold arrow keys for defined motion distance. \n"
"For details check setting page. "))
        self.groupB_switch.setTitle(_translate("MainWindow", "switch"))
        self.pushB_switch.setText(_translate("MainWindow", "next specimen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Specimen switch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
